### ISSUE TITLE
Option to override the maven repo used

### ISSUE THREAD

**Issue by cmagnuson** [paketo-buildpacks/new-relic#256]
It would be helpful if we could override the repo used to download the NewRelic agent.

## Describe the Enhancement

The user could specify a repo _somehow_ which would be used in place of the maven central repo currently hardcoded in the Java agent uri.

## Possible Solution

* An environment variable that could specify the repository base URL would be very nice to have.  
* I'm not familiar with how multiple build packs interact with each other, but another possibility could be using the repo settings from the maven buildpack https://github.com/paketo-buildpacks/maven

## Motivation

Maven Central can experience downtime and many development environments may only have access to a private Maven repo which acts as a mirror to Maven Central.

**Comment by dmikusa** [comment]
You can use a [Dependency Mirror](https://paketo.io/docs/howto/configuration/#dependency-mirrors) or you can use a [Dependency Mapping](https://paketo.io/docs/howto/configuration/#dependency-mappings). The former will point everything the buildpacks try to install to the mirror, the latter allows you to pick individual dependencies one at a time and point them elsewhere.

If you use the dependency mapping, the [binding-tool](https://github.com/dmikusa/binding-tool) cli can help create the bindings.

Hope that helps!

**Comment by cmagnuson** [comment]
I was not aware of that, that does exactly what I wanted.  Thanks @dmikusa !
