### ISSUE TITLE
Allow overriding newrelic.yml

### ISSUE THREAD

**Issue by cdowney** [paketo-buildpacks/new-relic#33]
The docs say the Java helper will contribute a default `newrelic.yml`. Is there a way to specify or override the `newrelic.yml` file?

**Comment by dmikusa** [comment]
Not through the buildpack, sorry. The buildpack just copies that file into the layer and configures the agent to locate it.

What you can do is override individual configuration settings though. That is the purpose of the helper. If will look for a binding at runtime with `type` of `NewRelic`. You can then set key/value properties in the binding. The helper maps those to env variables at runtime in the format `NEW_RELIC_<KEY>=<VALUE>` which, it's my understanding, that the agent will read and use to override values from the config file.

So you can set [these properties](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#General) through a binding.

**Comment by cdowney** [comment]
I follow, thank you for the response!

**Comment by dmikusa** [comment]
No problem. I'm going to close this. If you have other questions, feel free to open a new issue.
